version: "3.9"

volumes:
  nestjs-crm-postgres: {}

services:
  postgres:
    container_name: crm-postgres
    image: postgres
    ports:
      - '5431:5432'
    volumes:
      - nestjs-crm-postgres:/data/postgres
    env_file:
      - .env

#  api:
#    restart: unless-stopped
#    build:
#      context: .
#      dockerfile: Dockerfile
#      target: dev
#    ports:
#      - '5062:5062'
#    depends_on:
#      - postgres
#    env_file:
#      - .env
#    volumes:
#      - ./src:/app/src
#

# services:

#   # PostgreSQL Veritabanı
#   postgres:
#     image: postgres
#     restart: always
#     ports:
#       - "5432:5432"
#     volumes:
#       - ./postgres-data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_PASSWORD: 24262060
#       POSTGRES_USERNAME: postgres
#       POSTGRES_DATABASE: askadrovip

#   # NestJS Uygulaması
#   nestjs:
#     build: .
#     ports:
#       - "3000:3000"
#     depends_on: 
#       - postgres 
#     volumes:
#        - ./src:/app/src 
#     environment:
#       POSTGRES_HOST: postgres
#       POSTGRES_PORT: 5432
#       POSTGRES_USERNAME: postgres
#       POSTGRES_PASSWORD: 24262060
#       POSTGRES_DATABASE: askadrovip
