version: "3.9"

volumes:
  nestjs-crm-postgres: {}

services:
  keycloak:
    container_name: keycloak-askadrovip
    image: quay.io/keycloak/keycloak:25.0.1
    command: ["start-dev", "--import-realm"]
    environment:
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://postgres:5432/keycloak"
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: 24262060

      KC_REALM_NAME: askadrovip-realm

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - mynetwork
    depends_on:
      - postgres
    volumes:
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json:ro

  postgres:
    container_name: crm-postgres
    restart: always
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - nestjs-crm-postgres:/data/postgres
    env_file:
      - .env
    networks:
      - mynetwork
#
#  askadro-crm:
#    container_name: askadro-crm
#    restart: unless-stopped
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - '5062:5062'
#    depends_on:
#      - postgres
#    env_file:
#      - .env
#    volumes:
#      - ./src:/app/src
#    networks:
#      - mynetwork
#
#
networks:
  mynetwork:
    driver: bridge
