# version: "3.9"

# services:

#   # PostgreSQL Veritabanı
#   postgres:
#     image: postgres
#     restart: always
#     ports:
#       - "5432:5432"
#     volumes:
#       - ./postgres-data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_PASSWORD: 24262060
#       POSTGRES_USERNAME: postgres
#       POSTGRES_DATABASE: askadrovip

#   # NestJS Uygulaması
#   nestjs:
#     build: .
#     ports:
#       - "3000:3000"
#     depends_on: 
#       - postgres 
#     volumes:
#        - ./src:/app/src 
#     environment:
#       POSTGRES_HOST: postgres
#       POSTGRES_PORT: 5432
#       POSTGRES_USERNAME: postgres
#       POSTGRES_PASSWORD: 24262060
#       POSTGRES_DATABASE: askadrovip
