export const path:{
  job: {
    main: string,
    create: string,
    getOneJob: string,
    getJobs: string,
    updateJob: string,
    deleteJob: string,
    filterJob: string,
    searchJob: string,
  },
  company: {
    main: string,
    create: string,
    getOneCompany: string,
    getCompanies: string,
    updateCompany: string,
    deleteCompany: string,
    filterCompany: string,
    searchCompany: string,
    addAuthorized: string,
  },
  ticket: {
    main: string,
    create: string,
    getOneTicket: string,
    getTickets: string,
    crateCompanyTicket: string,
    updateTicket: string,
    deleteTicket: string,
    filterTicket: string,
  },
  users: {
    main: string,
    deletedUsers: string,
    user: string,
    userSearch: string,
    userJob: string,
    userCreate: string,
    userAddressCreate: string,
    userAddressUpdate: string,
    userDelete: string,
    userUpdate: string
    update_auth:string
  }
} = {
  job: {
    main: 'jobs',
    create: '/new',
    getOneJob: '/:id',
    getJobs: '/',
    updateJob: '/update/:id',
    deleteJob: '/delete/:id',
    filterJob: '/filter/all',
    searchJob: '/search',
  },
  company: {
    main: 'companies',
    create: '/new',
    getOneCompany: '/:id',
    getCompanies: '',
    updateCompany: '/update/:id',
    deleteCompany: '/delete/:id',
    filterCompany: '/filter/all',
    searchCompany: '/search/all',
    addAuthorized: '/new-authorized',
  },
  ticket: {
    main: 'tickets',
    create: '/new',
    getOneTicket: '/:id',
    getTickets: '/all',
    crateCompanyTicket: '/crate-company-ticket',
    updateTicket: '/update/:id',
    deleteTicket: '/delete/:id',
    filterTicket: '/filter/all',
  },
  users: {
    main: '',
    deletedUsers: '/deleted-users',
    user: 'user/:id',
    userSearch: 'user-search/:query',
    userJob: 'job/:id',
    userCreate: 'create',
    userDelete: 'delete/:id',
    userUpdate: 'update/:id',
    userAddressCreate: 'user-address-create/:id',
    userAddressUpdate: 'user-address-update/:userAddressId',
    update_auth:"update/auth/:userId"
  }
};